apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jNzBjMG9hOGN5a3ouZXUtbm9ydGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  db_username: YWRtaW4=
  db_password: Q2xvdWQxMjM=
